services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./chroma:/app/db
    environment:
      - PERSIST_DIR=/app/db
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
