apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: limemanas/vectormind-ai-backend:latest 
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi" 
            cpu: "500m"
          limits:
            memory: "1Gi" 
            cpu: "1" 
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379" 
        - name: CHROMA_HOST
          value: "chromadb-service" 
        - name: OLLAMA_BASE_URL
          value: "http://host.docker.internal:11434" 
        volumeMounts:
        - name: hf-cache
          mountPath: /root/.cache/huggingface
      volumes:
      - name: hf-cache
        emptyDir: {} # For production, replace with a PersistentVolumeClaim
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service 
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
