apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb-deployment
  labels:
    app: chromadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: chromadb/chroma
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: chromadb-data
          mountPath: /chroma/chroma 
      volumes:
      - name: chromadb-data
        emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb-service 
spec:
  selector:
    app: chromadb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
